import { Sparkles } from 'lucide-react';
import { cn } from '../ui/Button';

interface AIBannerProps {
    className?: string;
    confidence?: number;
}

export const AIBanner = ({ className, confidence }: AIBannerProps) => {
    return (
        <div className={cn(
            "bg-gradient-to-r from-violet-50 to-fuchsia-50 border border-violet-100 rounded-xl p-4 flex items-start gap-3",
            className
        )}>
            <div className="p-2 bg-white rounded-lg shadow-sm">
                <Sparkles className="w-5 h-5 text-violet-600" />
            </div>
            <div className="flex-1">
                <div className="flex items-center justify-between">
                    <h4 className="font-medium text-violet-900 text-sm flex items-center gap-2">
                        AI-Generated Insight
                        {confidence && (
                            <span className={cn(
                                "text-xs px-2 py-0.5 rounded-full border",
                                confidence > 90 ? "bg-green-50 text-green-700 border-green-200" :
                                    confidence > 70 ? "bg-amber-50 text-amber-700 border-amber-200" :
                                        "bg-red-50 text-red-700 border-red-200"
                            )}>
                                {confidence}% Confidence
                            </span>
                        )}
                    </h4>
                </div>
                <p className="text-xs text-violet-700 mt-1 max-w-prose">
                    This analysis is generated by AI and should be verified by a medical professional.
                    It is not a diagnosis.
                </p>
            </div>
        </div>
    );
};
